//  var products = [{ "name": "Hot Choc Vending", "image": "https://robohash.org/consequaturenimreprehenderit.png?size=200x300&set=set1", "price": "1.00" },
//     { "name": "Sambuca Cream", "image": "https://robohash.org/inearumeveniet.jpg?size=200x300&set=set1", "price": "2.45" },
//     { "name": "Wine - Pinot Grigio Collavini", "image": "https://robohash.org/illovoluptatibuscorrupti.png?size=200x300&set=set1", "price": "8.19" },
//     { "name": "Lettuce - Belgian Endive", "image": "https://robohash.org/autemnobiset.bmp?size=200x300&set=set1", "price": "1.73" },
//     { "name": "Ice Cream - Strawberry", "image": "https://robohash.org/quicommodidolorum.jpg?size=200x300&set=set1", "price": "6.71" },
//     { "name": "Wine - Niagara,vqa Reisling", "image": "https://robohash.org/architectonesciunttempora.png?size=200x300&set=set1", "price": "3.76" },
//     { "name": "Lamb - Sausage Casings", "image": "https://robohash.org/debitissuntpariatur.jpg?size=200x300&set=set1", "price": "3.95" },
//     { "name": "Icecream - Dstk Strw Chseck", "image": "https://robohash.org/atquerecusandaeut.bmp?size=200x300&set=set1", "price": "1.26" },
//     { "name": "Salmon - Whole, 4 - 6 Pounds", "image": "https://robohash.org/autnesciuntquia.png?size=200x300&set=set1", "price": "7.74" },
//     { "name": "Chevril", "image": "https://robohash.org/accusamusfacilisratione.png?size=200x300&set=set1", "price": "5.77" },
//     { "name": "Bread - Corn Muffaletta", "image": "https://robohash.org/autcorruptiquis.bmp?size=200x300&set=set1", "price": "5.56" },
//     { "name": "Syrup - Kahlua Chocolate", "image": "https://robohash.org/quisutnihil.png?size=200x300&set=set1", "price": "2.20" },
//     { "name": "Flour - Strong", "image": "https://robohash.org/doloremaspernaturmaxime.bmp?size=200x300&set=set1", "price": "5.82" },
//     { "name": "Jameson - Irish Whiskey", "image": "https://robohash.org/dignissimosaliquamnisi.jpg?size=200x300&set=set1", "price": "0.95" },
//     { "name": "Fuji Apples", "image": "https://robohash.org/laudantiumearumdeserunt.png?size=200x300&set=set1", "price": "7.42" },
//     { "name": "Pepsi - Diet, 355 Ml", "image": "https://robohash.org/eaquererumaut.png?size=200x300&set=set1", "price": "1.71" },
//     { "name": "Oil - Sunflower", "image": "https://robohash.org/idetrepudiandae.png?size=200x300&set=set1", "price": "6.52" },
//     { "name": "Beef - Diced", "image": "https://robohash.org/mollitiaanimipossimus.bmp?size=200x300&set=set1", "price": "8.30" },
//     { "name": "Vodka - Hot, Lnferno", "image": "https://robohash.org/modidelectusaliquid.png?size=200x300&set=set1", "price": "6.42" },
//     { "name": "Scampi Tail", "image": "https://robohash.org/doloressequiaut.bmp?size=200x300&set=set1", "price": "8.98" },
//     { "name": "Sauce - Mint", "image": "https://robohash.org/totamquisodit.bmp?size=200x300&set=set1", "price": "7.89" },
//     { "name": "Lemonade - Island Tea, 591 Ml", "image": "https://robohash.org/molestiaeautporro.png?size=200x300&set=set1", "price": "6.15" },
//     { "name": "Grenadillo", "image": "https://robohash.org/etfugiatfacere.jpg?size=200x300&set=set1", "price": "8.61" },
//     { "name": "Table Cloth 53x69 White", "image": "https://robohash.org/eavoluptatemipsum.png?size=200x300&set=set1", "price": "3.88" },
//     { "name": "Oil - Food, Lacquer Spray", "image": "https://robohash.org/quaseaqueoptio.jpg?size=200x300&set=set1", "price": "1.26" },
//     { "name": "Pasta - Linguini, Dry", "image": "https://robohash.org/temporibusconsequaturipsum.png?size=200x300&set=set1", "price": "6.83" },
//     { "name": "Wine - White, Gewurtzraminer", "image": "https://robohash.org/atoccaecatiodit.bmp?size=200x300&set=set1", "price": "7.64" },
//     { "name": "Compound - Pear", "image": "https://robohash.org/velitdoloresfugit.png?size=200x300&set=set1", "price": "3.08" },
//     { "name": "Mustard - Dry, Powder", "image": "https://robohash.org/distinctioipsamet.bmp?size=200x300&set=set1", "price": "6.55" },
//     { "name": "Soupcontfoam16oz 116con", "image": "https://robohash.org/namnequedolores.bmp?size=200x300&set=set1", "price": "6.86" },
//     { "name": "Flour - Buckwheat, Dark", "image": "https://robohash.org/eligendiidnihil.png?size=200x300&set=set1", "price": "4.72" },
//     { "name": "Jagermeister", "image": "https://robohash.org/etquisminus.jpg?size=200x300&set=set1", "price": "0.34" },
//     { "name": "Propel Sport Drink", "image": "https://robohash.org/solutamagnamhic.bmp?size=200x300&set=set1", "price": "0.25" },
//     { "name": "Curry Powder", "image": "https://robohash.org/voluptatespariaturvoluptatem.jpg?size=200x300&set=set1", "price": "1.36" },
//     { "name": "Easy Off Oven Cleaner", "image": "https://robohash.org/nesciuntvoluptatemhic.bmp?size=200x300&set=set1", "price": "0.02" },
//     { "name": "Sponge Cake Mix - Vanilla", "image": "https://robohash.org/numquamconsecteturblanditiis.bmp?size=200x300&set=set1", "price": "9.07" }]